### ISSUE TITLE
keyboard input covers sharedata and buydata page

### ISSUE THREAD

**Issue by mayokunadeniyi** [Fstackdevio/Netsurf-Mobile#1]
* On clicking any textinputfield on both sharedata and buydata pages, the keyboard pops up and covers the entire screen leaving the user blind to what is being typed.

**Comment by mayokunadeniyi** [comment]
The error discovered was that the cardview had too much information to fit on a screen for both pages i.e. wasn't scroll-able. To fix this, a scrollview needs to be implemented on both pages.

**Comment by moak13** [comment]
it should be fixed as scroll view has been implemented
